# docker container to run an express backend server

FROM node:21-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./

RUN npm install
# Bundle app source
COPY . .

# Expose port 3000
EXPOSE 3000

# Run migrations and start the app
CMD [ "sh", "-c", "npm run start:dev" ]